global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Add alertmanager targets here when ready
          # - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: wonder-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - wonder-backend:8080

  - job_name: cadvisor
    static_configs:
      - targets:
          - wonder-cadvisor:8080
