# Development Environment Configuration
app:
  name: "wonder"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  enable_cors: true

database:
  host: "localhost"
  port: 5432
  username: "dev"
  password: "dev"
  database: "wonder_dev"
  ssl_mode: "disable"
  timezone: "UTC"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "1h"
  conn_max_idle_time: "30m"
  log_level: "info"

log:
  # Log level: debug, info, warn, error
  level: "info"
  # Log format: json, text
  format: "json"
  # Log output: stdout, file, both
  output: "file"
  # Path to log file (required when output is "file" or "both")
  file_path: "./logs/wonder.log"
  # Enable file logging (optional, defaults to false)
  enable_file: true
  # Service name for logging context
  service_name: "wonder"

id:
  service_type: "user"
  instance_id: 0
  node_id: 1

external:
  redis:
    host: "localhost"
    port: 6379
    password: ""
    database: 0

  email:
    provider: "smtp"
    host: "smtp.gmail.com"
    port: 587
    username: ""
    password: ""