# Testing Environment Configuration
app:
  name: "wonder"
  version: "1.0.0"
  environment: "testing"
  debug: false

server:
  host: "localhost"
  port: 8081
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "30s"
  enable_cors: true

database:
  host: "localhost"
  port: 5432
  username: "test"
  password: "test"
  database: "wonder_test"
  ssl_mode: "disable"
  timezone: "UTC"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "30m"
  conn_max_idle_time: "15m"
  log_level: "warn"

log:
  level: "warn"
  format: "json"
  output: "stdout"
  enable_file: false
  file_path: "logs/test.log"
  service_name: "wonder"
  enable_tracing: true
  max_file_size: 100  # MB
  max_backups: 3
  max_age: 28  # days
  compress: true

id:
  service_type: "user"
  instance_id: 0
  node_id: 100

external:
  redis:
    host: "localhost"
    port: 6379
    password: ""
    database: 1

  email:
    provider: "mock"
    host: "localhost"
    port: 1025
    username: "test"
    password: "test"