// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/snowflake/id/generator.go
//
// Generated by this command:
//
//	mockgen -source=pkg/snowflake/id/generator.go -destination=pkg/snowflake/id/mocks/mock_generator.go -package=mocks Generator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	id "github.com/cctw-zed/wonder/pkg/snowflake/id"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
	isgomock struct{}
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockGenerator) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGenerator)(nil).Generate))
}

// GenerateInt64 mocks base method.
func (m *MockGenerator) GenerateInt64() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInt64")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GenerateInt64 indicates an expected call of GenerateInt64.
func (mr *MockGeneratorMockRecorder) GenerateInt64() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInt64", reflect.TypeOf((*MockGenerator)(nil).GenerateInt64))
}

// GetNodeID mocks base method.
func (m *MockGenerator) GetNodeID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetNodeID indicates an expected call of GetNodeID.
func (mr *MockGeneratorMockRecorder) GetNodeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeID", reflect.TypeOf((*MockGenerator)(nil).GetNodeID))
}

// GetServiceType mocks base method.
func (m *MockGenerator) GetServiceType() id.ServiceType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceType")
	ret0, _ := ret[0].(id.ServiceType)
	return ret0
}

// GetServiceType indicates an expected call of GetServiceType.
func (mr *MockGeneratorMockRecorder) GetServiceType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceType", reflect.TypeOf((*MockGenerator)(nil).GetServiceType))
}
