# Wonder Application Configuration Example - File Logging
# This example shows how to configure logging to file

app:
  name: "wonder"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  enable_cors: true

log:
  # Log level: debug, info, warn, error
  level: "info"

  # Log format: json, text
  format: "json"

  # Log output: stdout, file, both
  output: "file"

  # Path to log file (required when output is "file" or "both")
  file_path: "./logs/wonder.log"

  # Enable file logging (optional, defaults to false)
  enable_file: true

  # Service name for logging context
  service_name: "wonder-api"

database:
  host: "localhost"
  port: 5432
  username: "wonder"
  password: "wonder123"
  database: "wonder_db"
  ssl_mode: "disable"
  timezone: "UTC"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

id:
  service_type: "user"
  instance_id: 1
  node_id: 1

external:
  # External service configurations can be added here
  # example_api:
  #   base_url: "https://api.example.com"
  #   timeout: 30s
  #   api_key: "your-api-key"